Added Axios setup, Pokemon card component, and random Pokemon data fetcher
AnujMishraGit/PokePro_Anuj pull request #1
Opened 2023-04-30 04:11 UTC by AnujMishraGit

Description: This pull request adds  new components to the project:
**I am using normal CSS because the tailwind issue is not fixed yet and also not using redux right now I need to go through redux toolkit doc once **

_Please go to  http://localhost:5173/search _ to  see the changes _I have slitely changed the design but we can change it if this doesn't feel good_

-  Axios setup: sets up Axios to make API requests to PokeAPI.
- Pokemon card component: displays information about a given Pokemon, including its name and image.
- Random Pokemon data fetcher: fetches data about 20 Pokemon from PokeAPI and passes it to the Pokemon card component.
- I am facing an issue where the Pokemon color wasn't being correctly retrieved for certain Pokemon (e.g. with ID 11).
Here is the documentation snippet about Pokemon color
Pokemon Colors (endpoint)
Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is usually the color most apparent or covering each Pokémon's body. No orange category exists; Pokémon that are primarily orange are listed as red or brown.

GET https://pokeapi.co/api/v2/pokemon-color/{id or name}/
![Screenshot from 2023-04-30 09-12-14](https://user-images.githubusercontent.com/131875641/235335098-17810568-cc6c-40d1-9982-575ee6536c8c.png)

2023-05-02 17:41 UTC, riyaz942 requested changes
Added in couple of feedback, do check it out.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/App.css
> +    align-items:center;
Can we use the helper classes provided by tailwind instead.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/App.css
> +    height:80vh;
Just a pointer, it is generally a good practice to give the control to the individual page, the containers would fill in the spaces and the individual page can decide if it wants padding or have an overflow, we can create a page container of sort for those cases. but for this example I think we can move forward with it.

But since we are using flexbox lets use that to fill in the container. 

```
flex: 1;
align-self: stretch;
```

Then we can specify some padding to get the current result.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/App.css
> +  margin-bottom: 10px;
Not sure why margin-bottom is used, can we get rid of this ?

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/App.css
> +  overflow-x: hidden;
use overflow: auto, if you see overflow on the x axis then there is some layouting miss haps in the page.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/App.tsx
> +import Footer from "./components/Footer/Footer";
Not now but later on look into creating alias for importing components as absolute imports.

It is generally a pain if you are moving code and then have to change the path of the import. or if there some components at the back of the directories you could then avoid using `../`

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/Search.tsx
> +  const [pokemonColors, setPokemonsColors]= useState<string[]>([]);
Better to have a single state that holds all the pokemon properties. Also create type for it.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/Search.tsx
> +}
Move this to a d.ts file

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/Search.tsx
> +      const response = await axios.get("https://pokeapi.co/api/v2/pokemon");
Create a constant for the API endpoints in a seperate ts file.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/Search.tsx
> +        const response = await axios.get<PokemonDetails>(pokemon.url);
We can move this API calls in the above use effect and and use it after the listing API call.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/Search.tsx
> +          const response = await axios.get<PokemonColorDetails>(`https://pokeapi.co/api/v2/pokemon-species/${index}`);
We can move this API in the same use effect, as the listing API. 
It would be best to use Promise.All to combine both the species and pokemon details API call. will make the code a little bit cleaner.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/assets/assets/balbasaur.png
I guess we can remove these assets as well if its not required.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/search.css
> +    flex-wrap: wrap;
better to use the tailwind classes so we can avoid creating a css or scss file. would also make the development a little faster

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/Search.tsx
> +    <div className="card-container">
Also these classname would be colliding with other classes if the have the same name, it would be better to use css modules or like a unique naming convention like BEM in these cases to avoid collision, but if you completely use tailwind classnames then it is all good.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/Pages/Search/Search.tsx
> +        <div key={index} className="card">
Use a better unique identifier then index. maybe the pokemon id or the name

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/assets/assets/pokeball-loader.gif
If the asset is not used you can remove them.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Background/Background.tsx
> +}
We can shorten it like this.

```suggestion
const Background = () =>  (
    <div className='background'>
      {/* <img src={pokeball} alt="pokeball" className="pokeball pokeball-1"/>' */}
      <img src={pokeball2} alt="pokeball2" className="pokeball pokeball2"/>'
      <img src={pokeball2} alt="pokeball2" className="pokeball pokeball-2"/>'
      {/* <img src={pokeball} alt="pokeball" className="pokeball pokeball-1"/>' */}
      {/* <img src={pokeball} alt="pokeball" className="pokeball pokeball-1"/>' */}
      <img src={pokeball2} alt="pokeball" className="pokeball pokeball-2"/>'
      <img src={pokeball2} alt="pokeball" className="pokeball pokeball-2"/>'
      <img src={pokeball2} alt="pokeball" className="pokeball pokeball-2"/>'
      <img src={pokeball2} alt="pokeball" className="pokeball pokeball-2"/>'
      <img src={pokeball2} alt="pokeball" className="pokeball pokeball-2"/>'
      <img src={pokeball2} alt="pokeball" className="pokeball pokeball-2"/>'
     
      <img src={pokeball2} alt="pokeball" className="pokeball pokeball-2"/>'
      {/* <img src={pokeball} alt="pokeball" className="pokeball pokeball-1"/>' */}
    </div>
  )
```

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Background/Background.tsx
> +      {/* <img src={pokeball} alt="pokeball" className="pokeball pokeball-1"/>' */}
Do remove the comment code if its not required.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Background/background.css
> +    max-inline-size: 100%;
use `objectFit` property to avoid stretching the image.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Card/Card.tsx
> +            <img src={imgURL} alt={name}  className="pokeImage"/>
Also look into having a default image to show till the API call is being made. It shows broken images on page load, that can be avoid.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Card/Card.tsx
> +function Card({name,imgURL,prominentColor ,ability,}:cardProps) {
Can we use the `React.FC` type here
Let's also name the component to a specific name, like PokemonCard or Something.

```suggestion
const Card: React.FC<CardProps> = ({name, imgURL, prominentColor ,ability}) => {
```

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Card/card.css
> +    height: 20em;
Can we rather use px here.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Card/card.css
> +}
I don't think we would require this div and this class here, we can directly use the image tag and manipulate the style on the image tag.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Card/Card.tsx
> +            <img src={imgURL} alt={name}  className="pokeImage"/>
Also don't forget to use`objectFit` property.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Header/Header.tsx
> +  return (
If the component is just returning the jsx we can write it like this.

```suggestion
  const Header: React.FC = () => (<header></header>)
```

Without the return

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/Header/header.css
> +    width: 100vw;
Better to use a fixed height in PX in this case since we are using flex on the page container.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/components/InputBar/InputBar.jsx
> +function InputBar() {
do use the React.FC type

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/utils/debounce.ts
> +const debounce = (fn: Function, timeout: number) => {
You can rather import loadash and use loadash's debounce.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/utils/baseUrl.ts
> +export const pokemonAPI = "https://pokeapi.co/api/v2";
I like the constants.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/index.css
> +  );
Just checking if this is being used or not. if not then we can remove them.

2023-05-02 17:41 UTC, riyaz942 commented on pokepro/src/index.css
>    font-weight: 400;
Do check out on using the roboto fonts, that would really popout the UI.

2023-05-03 06:51 UTC, AnujMishraGit commented on pokepro/src/Pages/Search/Search.tsx
> +  const [pokemonColors, setPokemonsColors]= useState<string[]>([]);
I have changed the code to use redux store now,  but I will keep this in mind for next time

2023-05-03 07:06 UTC, AnujMishraGit commented on pokepro/src/Pages/Search/Search.tsx
> +    <div className="card-container">
ok I am switching to tailwind from now on fo there will be an improvement on this part.

2023-05-04 13:58 UTC, merged